#release configuration
#Thu Apr 16 14:26:47 CEST 2026
projectVersionPolicyId=default
project.rel.sc.fiji\:ome-zarr-fiji=0.3.1
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
pinExternals=false
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
project.scm.sc.fiji\:ome-zarr-fiji.developerConnection=scm\:git\:git@github.com\:BioImageTools/ome-zarr-fiji-java
project.scm.sc.fiji\:ome-zarr-fiji.tag=HEAD
exec.activateProfiles=deploy-to-scijava
pushChanges=false
project.scm.sc.fiji\:ome-zarr-fiji.connection=scm\:git\:git\://github.com/BioImageTools/ome-zarr-fiji-java
remoteTagging=true
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
releaseStrategyId=default
project.scm.sc.fiji\:ome-zarr-fiji.url=https\://github.com/BioImageTools/ome-zarr-fiji-java
completedPhase=end-release
scm.url=scm\:git\:https\://github.com/BioImageTools/ome-zarr-fiji-java
scm.developmentCommitComment=@{prefix} prepare for next development iteration
exec.additionalArguments=-Dgpg.skip\=true -Dmaven.test.skip\=true
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.dev.sc.fiji\:ome-zarr-fiji=0.3.2-SNAPSHOT
scm.tag=ome-zarr-fiji-0.3.1
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean verify
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
exec.pomFileName=pom.xml
